#!/bin/bash
# Generate objects.txt File
pd \
  -batch \
  -open _objectlist.pd \
  -send "METAFILE ${librarydir}/${library}-meta.pd" 2>&1 | \
  sed 's/ /    /' \
  > "${workspacedir}/${library}-v${version}-objects.txt"

(
  cd $librarydir

  # clean build area
  make clean

  # clean target area
  rm -rf ${workspacedir}/${library}

  # copy sources
  mkdir -p ${workspacedir}/${library}
  git-archive-all.sh -- - | tar -x -C ${workspacedir}/${library}
  rm -rf ${workspacedir}/${library}/.gitmodules
   
  # create version-file
  echo "$version" > ${workspacedir}/${library}/VERSION.txt
  
  # copy
  #rsync -av --delete ${workspacedir}/${library} ${remotehost}:${remoteworkspacedir}/.
)
