#!/bin/bash
pdsrcdir=~/pd-src
pddir=${pdsrcdir}/pd/
platform=$(basename $(pwd))
workspacedir=${pdsrcdir}/workspace/${platform}
remoteworkspacedir=pd-src/workspace/${platform}
remotehost=roman@netpd.org
datecommand="date -d @"
MAKEFLAGS="CC=x86_64-linux-gnu-gcc-7"
