#!/bin/bash
pdsrcdir=~/pd-src
pddir=/mingw64
platform=$(basename $(pwd))
workspacedir=${pdsrcdir}/workspace/${platform}
remoteworkspacedir=${workspacedir}
remotehost=roman@netpd.org
datecommand="date -d @"
localdep=false
localdep_platform=windows
MAKEFLAGS="extension=m_amd64"
