#!/bin/bash
(
  cd $librarydir
  # clean target area
  rm -rf ${workspacedir}/${library}
  
  # build
  if ! ( make \
        UNAME=MINGW \
        CC=i686-w64-mingw32-gcc \
        PD_PATH=${pddir} CFLAGS="" \
	PD_INCLUDE=${pddir}/src \
        LDFLAGS="-Wl,-l:pd.dll -Wl,--enable-auto-image-base" \
        LIBS="-lpthread" \
	pkglibdir=${workspacedir} \
	install )
  then
    echo "error while building"
    exit 1
  fi

  # clean build area
  make UNAME=MINGW LDFLAGS="-Wl,-l:pd.dll -Wl,--enable-auto-image-base" clean
  
  # create version-file
  echo "$version" > ${workspacedir}/${library}/VERSION.txt
  
  # copy
  rsync -av --delete ${workspacedir}/${library} ${remotehost}:${remoteworkspacedir}/.
)
