#!/bin/bash
(
  cd $librarydir
  # clean target area
  rm -rf ${workspacedir}/${library}
  
  # build
  if ! ( make \
        $MAKEFLAGS \
        uname=MINGW \
        CC=i686-w64-mingw32-gcc \
        pdbinpath=${pddir}/bin/ \
        pdincludepath=${pddir}/src/ \
        CFLAGS="" \
	pkglibdir=${workspacedir}
        )
  then
    echo "error while building"
    exit 1
  fi

  # install
  if ! ( make \
        $MAKEFLAGS \
        uname=MINGW \
        CC=i686-w64-mingw32-gcc \
        pdbinpath=${pddir}/bin/ \
        pdincludepath=${pddir}/src/ \
        CFLAGS="" \
	pkglibdir=${workspacedir} \
	install )
  then
    echo "error while installing"
    exit 1
  fi

  # clean build area
  make uname=MINGW clean
  
  # create version-file
  echo "$version" > ${workspacedir}/${library}/VERSION.txt
  
  # copy
  rsync -av --delete ${workspacedir}/${library} ${remotehost}:${remoteworkspacedir}/.
)
