#!/bin/bash
pdsrcdir=/home/roman/pd-src
pddir=${pdsrcdir}/w32/pd
platform=$(basename $(pwd))
workspacedir=${pdsrcdir}/workspace/${platform}
remoteworkspacedir=${workspacedir}
remotehost=roman@netpd.org
