#!/bin/bash
pdsrcdir=~/pd-src
pddir=~/Downloads/pd-0.51-4-i386
platform=$(basename $(pwd))
workspacedir=${pdsrcdir}/workspace/${platform}
remoteworkspacedir=${workspacedir}
remotehost=roman@netpd.org
datecommand="date -d @"
MAKEFLAGS="uname=MINGW CC=i686-w64-mingw32-gcc pdbinpath=${pddir}/bin/"
