#!/bin/bash
(
  cd $librarydir
  # clean target area
  rm -rf ${workspacedir}/${library}

  # build
  echo "====================================================="
  echo "BUILD"
  echo "====================================================="
  echo "make $MAKEFLAGS PDDIR=${pddir} PDLIBDIR=${workspacedir}"
  if ! make $MAKEFLAGS PDDIR=${pddir} PDLIBDIR=${workspacedir}
  then
    echo "error while building"
    exit 1
  fi

  # install
  echo "====================================================="
  echo "INSTALL"
  echo "====================================================="
  echo "make $MAKEFLAGS PDDIR=${pddir} PDLIBDIR=${workspacedir} install"
  if ! make $MAKEFLAGS PDDIR=${pddir} PDLIBDIR=${workspacedir} install
  then
    echo "error while installing"
    exit 1
  fi

  # localdep
  if $localdep; then
    echo "====================================================="
    echo "LOCALDEP"
    echo "====================================================="
    echo "make $MAKEFLAGS PDDIR=${pddir} PDLIBDIR=${workspacedir} localdep_${localdep_platform}"
    if ! make $MAKEFLAGS PDDIR=${pddir} PDLIBDIR=${workspacedir} localdep_${localdep_platform}
    then
      echo "error while adding dependencies locally"
      exit 1
    fi
  fi

  # clean build area
  echo "====================================================="
  echo "CLEAN"
  echo "====================================================="
  echo "make $MAKEFLAGS clean"
  make $MAKEFLAGS clean

  # create version-file
  echo "$version" > ${workspacedir}/${library}/VERSION.txt

  # copy
  echo "====================================================="
  echo "UPLOAD"
  echo "====================================================="

  echo "rsync -av --delete ${workspacedir}/${library} ${remotehost}:${remoteworkspacedir}/."
  rsync -av --delete ${workspacedir}/${library} ${remotehost}:${remoteworkspacedir}/.
)
