#!/bin/bash
pdsrcdir=/Users/roman/pd-src
pddir=${pdsrcdir}/pd/
platform=$(basename $(pwd))
workspacedir=${pdsrcdir}/workspace/${platform}
remoteworkspacedir=/home/roman/pd-src/workspace/${platform}
remotehost=roman@netpd.org
