#!/bin/bash
pdsrcdir=~/pd-src
pddir=${pdsrcdir}/pd/
platform=$(basename $(pwd))
workspacedir=${pdsrcdir}/workspace/${platform}
remoteworkspacedir=pd-src/workspace/${platform}
remotehost=roman@netpd.org
datecommand="date -d @"
localdep=false
localdep_platform=linux
MAKEFLAGS="CC=arm-linux-gnueabihf-gcc CFLAGS=\"-march=armv7\" extension=l_arm"
