#!/bin/bash
pdsrcdir=~/pd-src
pddir=${pdsrcdir}/pd/
platform=$(basename $(pwd))
workspacedir=${pdsrcdir}/workspace/${platform}
remoteworkspacedir=pd-src/workspace/${platform}
remotehost=roman@netpd.org
datecommand="date -d @"
MAKEFLAGS="CC=arm-linux-gnueabihf-gcc-9 CFLAGS=\"-march=armv7\""
