#!/bin/bash
pdsrcdir=~/pd-src
pddir=${pdsrcdir}/pd/
platform=$(basename $(pwd))
workspacedir=${pdsrcdir}/workspace/${platform}
remoteworkspacedir=pd-src/workspace/${platform}
remotehost=roman@netpd.org
datecommand="date -d @"
localdep=false
localdep_platform=linux
MAKEFLAGS="CC=i686-linux-gnu-gcc extension=l_i386"
