#!/bin/bash
(
  cd $librarydir
  # clean target area
  rm -rf ${workspacedir}/${library}
  
  # build
  if ! make LIBRARY_NAME=${library} PD_PATH=${pddir} pkglibdir=${workspacedir} install
  then
    echo "error while building"
    exit 1
  fi
  
  # clean build area
  make clean
  
  # create version-file
  echo "$version" > ${workspacedir}/${library}/VERSION.txt
  
  # copy
  rsync -av --delete ${workspacedir}/${library} ${remotehost}:${remoteworkspacedir}/.
)
